version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/app:cached
        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity
        # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
        network_mode: service:postgres
    postgres:
        image: postgres:10
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: delivery-date-provider
        ports:
            - 5432:5432
        container_name: postgres
